#!/bin/sh
# 在6in4隧道里面配置好ISATAP，不要问怎么配，都是41号协议本质上是一样的
# Napt66 支持的网段仅为fc00:101:101::/48, 不要使用其他网段。多子网可以使用fc00:101:101:[1-xxxx]::/64 子网段。
# 把下面的脚本粘贴到WAN启动后，然后重启路由器
local_wan_v4_addr=$(curl -4 -s https://api.ip.sb/ip)
ip -6 addr replace 2001:da8:d800:9:200:5efe:$local_wan_v4_addr dev sit1
insmod /lib/modules/$(uname -r)/kernel/net/napt66/napt66.ko wan_if=sit1
